server:
  address:     ":10088"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  accessLogEnabled: false
  errorLogEnabled: false
  DumpRouterMap : true

logger:
  path:    "logs/default"
  level:   "all"
  stdout:  true
  
database:
  default:
#     link:   "pgsql:user=gfvben password=JBprEMNHJ7Md host=47.116.71.73 port=5432 dbname=gfvben sslmode=disable"
    link:  "mysql:gf-vben:rdSWTt3dsLMTMHhE@tcp(114.115.157.254:3306)/gf-vben"
    debug:  true
