server:
  address:     ":10088"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  default:
    link:   "pgsql:user=gfvben password=JBprEMNHJ7Md host=47.116.71.73 port=5432 dbname=gfvben sslmode=disable"
    debug:  true

gfcli:
  gen:
    dao:
      - link:     "pgsql:user=gfvben password=JBprEMNHJ7Md host=47.116.71.73 port=5432 dbname=gfvben sslmode=disable"
        path:   "./app"