
gfcli:
  gen:
    dao:
      - link:  "mysql:gf-vben:rdSWTt3dsLMTMHhE@tcp(114.115.157.254:3306)/gf-vben"

  build:
    name: "gf-vben"
    arch: "arm"
    system: "linux"
    version: "v1.0.0"
    output: "./bin"
    extra: ""
