
gfcli:
  gen:
    dao:
      - link:  "mysql:vben:ZmdjwPdb3BBPsXhN@tcp(114.115.157.254:3306)/vben"

  build:
    name: "gf-vben"
    arch: "arm"
    system: "linux"
    version: "v1.0.0"
    output: "./bin"
    extra: ""
